### ISSUE TITLE
No promotion?

### ISSUE THREAD

**Issue by horatio-sans-serif** [alexgenaud/twine#3]
> it is often faster and infinitely easier to bring failed
> masters back online than to reconfigure slaves, masters, and clients.

That assumes that the data on a partition/node is recoverable from the node or that offsite backups are in-place to replace a deceased node.  Thoughts?

**Comment by alexgenaud** [comment]
True.

However, I think master/slaves just re-invents RAID-1. But poorly. Swapping masters and slaves is easy enough. However, I've found that keeping the clients in sync is a real pain.

A master fails. Then client writes fail. Clients continue to poll some STATUS source (race condition). A monitor performs master/slave swap and updates the STATUS source (same race condition).

vs.

A master fails. Then client writes fail. A monitor brings the master back online.

If you've only got one master, then by all means replicate it. However, if your application goes through the trouble of partitions/shards, you might as well take it to the extreme: RAID your data, back it up religiously, and partition excessively.

You are correct that if a machine (rather than just a Redis instance) goes down, my solution requires the machine to come back online - or another from backup.

I posit that if the business cost of hardware failure is greater than the cost of avoiding it, then Redis may be the wrong solution to the problem. A product like Riak, Cassandra, and the like would be a better fit.

**Comment by horatio-sans-serif** [comment]
> RAID your data, back it up religiously, and partition excessively

I think I understand more of your mindset on this now.

> A monitor brings the master back online.

So you are protecting against Redis itself crashing then?

> I posit that if the business cost of hardware failure [...]

I'm not concerned about hardware replacement costs.  I'm more concerned about only having a single copy of some key lost due to an unrecoverable hardware failure.  Recovery from backups would suffice in such a case.  Granted, if I'm concerned about super high availability then a single copy on a single shard/partition is not going to cut it.  

Thanks.

**Comment by alexgenaud** [comment]
Hi Brian,

> So you are protecting against
> Redis itself crashing then?

Yes. Also, Monit will restart all services when the machine comes back online. While a master is down, writes will fail as expected.

However, with slave replication and failover promotion, there is possibility of getting a successful write response but in fact loose your data during a slave/master de/promotion or replication overwrite due race conditions.

Consider the fact that simply because you MIGHT switch a slave to a master, then all clients will constantly have to poll some status node. You necessarily introduce a race condition in which the client polls the status and writes to a redis node while a monitor updates the status and promotes slaves to masters.

But you are right, without slave replication, there is no data safety during catastrophic hardware failure, such as machine catching on fire.

> I'm more concerned about only having a
> single copy of some key lost due to an
> unrecoverable hardware failure.

In that case slave replication to another machine should reduce your risk of data failure (and perhaps I'll passive slave replication easy in twine). But I still recommend against a real-time monitor and status regime promoting the slave to master for the reasons stated above.

If a data storage solution requires zero interruption and zero data loss during catastrophic hardware failure, I feel that Redis is a poor choice. I believe you are looking for 'guaranteed write, eventually consistent reads' - which Redis does not support.

**Comment by horatio-sans-serif** [comment]
> If a data storage solution requires zero interruption and zero data loss during catastrophic hardware failure, I feel that Redis is a poor choice.

Perhaps that is true at this time.  However, I'm playing with the notion of proxying client access through a HA soluation: a Redis-protocol-aware proxy that monitors for downtime, and manages slave promotion.  

Should be a fun experiment and avoids any race conditions.  It adds a tiny bit of latency but that is a tradeoff for _this_ HA solution.

We'll see how it pans out.

![draft idea](http://fictorial.com/011.png)

![draft idea](http://fictorial.com/012.png)

**Comment by alexgenaud** [comment]
Fascinating. But what/who is monitoring the HA-proxy?

I wrote about a similar solution (client side sans proxy) on the Redis mailing list. I created these ugly pecking order algorithms just to keep track of which monitor was both alive and in charge of the cluster health (given a handful of monitors).

Another idea I toyed with was writing to multiple masters (master-master replication via client) but had no mechanism to reconciling differences (which I think should only be handled in Redis internally).

A side effect of replicating slaves on other machines is that you can then read from those slaves and balance the load. But if you have many partitions of masters and slaves evenly distributed across many machines, I don't see any advantage to ever read from a slave. Simply because master reads are guaranteed consistent. The 'load balance' effect of reading from slaves could just as easily be accomplished reading from smaller masters (more shards).

I am not proposing eliminating the slaves (for data safety and promotion). However, I do suggest that each machine should have far more partitions (redis master instances) than CPU cores (for optimal process cycle usage). In that scenario, reading from a slave does not provide any advantage over always reading from the master instead.

**Comment by horatio-sans-serif** [comment]
I avoid sharding my datasets since a subset of Redis commands are ineffective; anything that requires multiple keys like SMOVE, SORT, and RENAME.  Thus, the above proxy would apply to unsharded Redis.

To monitor the proxy one would use anything like supervisor, god, monit, daemontools, etc.  At some point you have to stop with multiple layers of redundancy/HA safeguards.  What monitors monit?  Who supervises supervisor?  

With a sharded configuration that also uses slaves, I suppose you end up replicating (ha!) the shard architecture of MongoDB wherein each shard has a master and a slave.  I don't love that given 1) shards (above); 2) expense for requiring 2x the hosts to buy/lease.

**Comment by alexgenaud** [comment]
> At some point you have to stop with multiple layers
> of redundancy/HA safeguards. What monitors monit?

Ultimately, you need a network of monitors monitoring each other, or no monitor abstraction at all. If you don't have a network of proxies monitoring all other proxies, what is the purpose of the proxy in the first place? Isn't it just one more thing that can fail? Is it to separate the master/slave handling to a network accessible process rather than a library used by your client? Doesn't single proxy represent a single point of failure and thus render slave replication irrelevant in regard to availability?

> shard... expense for requiring 2x the hosts to buy/lease.

Sharding does not increase hardware requirements. Replication does.

**Comment by horatio-sans-serif** [comment]
Well, the point of my proposed proxy was to encapsulate knowledge of which redis instance in a master-slave configuration was the current master such that a client just uses the proxy. A single proxy would of course be a single point of failure. One can use a number of things here: heartbeat, wackamole, etc.

> Sharding does not increase hardware requirements. Replication does.

In context, I was saying how a sharded redis cluster wherein each key is located on a single shard offers no fault tolerance. Adding master-slave replication per shard makes the system similar to mongodb. Thus, you end up with `|shards| * 2` hosts for single-slave-per-shard. That's all.

**Comment by alexgenaud** [comment]
So much has changed in the past decade !
